# Generated by Django 6.0.2 on 2026-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Unknown Company', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
