# Generated by Django 6.0.6 on 2026-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_created_at_job_description_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
