# Generated by Django 6.0.6 on 2026-07-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_is_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='target',
        ),
    ]
