# Generated by Django 6.0.6 on 2026-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
